#!/usr/bin/env bash
# One-shot server setup for the School Management API on a fresh
# Oracle Cloud Always Free instance (Ubuntu 22.04/24.04 or Oracle Linux, ARM or x86).
#
# Run it from inside the project directory on the server:
#
#   cd /opt/school-api
#   sudo bash bootstrap-oracle.sh                      # plain HTTP on the IP
#   sudo bash bootstrap-oracle.sh api.yourschool.com   # + free HTTPS certificate
#
# Safe to re-run: it skips whatever is already done and never overwrites
# an existing .env.production.
set -euo pipefail

SITE_ADDRESS="${1:-:80}"
TLS_EMAIL="${2:-ops@example.invalid}"
APP_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_FILE="$APP_DIR/docker-compose.prod.yml"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m !! %s\033[0m\n' "$*"; }
die() { printf '\033[1;31m !! %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run with sudo"
[ -f "$COMPOSE_FILE" ] || die "docker-compose.prod.yml not found in $APP_DIR"
[ -f "$APP_DIR/schema.sql" ] || die "schema.sql not found in $APP_DIR -- did the upload finish?"

# ---------------------------------------------------------------- packages
if command -v apt-get >/dev/null 2>&1; then
  PKG=apt
else
  PKG=dnf
fi

log "Installing base packages"
if [ "$PKG" = apt ]; then
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl openssl iptables-persistent >/dev/null
else
  dnf install -y -q ca-certificates curl openssl >/dev/null
fi

# ------------------------------------------------------------------ docker
if command -v docker >/dev/null 2>&1; then
  log "Docker already installed ($(docker --version))"
else
  log "Installing Docker"
  curl -fsSL https://get.docker.com | sh
fi
systemctl enable --now docker

docker compose version >/dev/null 2>&1 || die "docker compose plugin missing"

# add the login user to the docker group so they can skip sudo next time
LOGIN_USER="${SUDO_USER:-}"
if [ -n "$LOGIN_USER" ] && [ "$LOGIN_USER" != root ]; then
  usermod -aG docker "$LOGIN_USER" || true
  log "Added $LOGIN_USER to the docker group (log out and back in to use it)"
fi

# -------------------------------------------------------------------- swap
# Oracle images ship with no swap. MySQL + build steps appreciate a little.
if ! swapon --show | grep -q .; then
  log "Creating 2 GB swap file"
  fallocate -l 2G /swapfile || dd if=/dev/zero of=/swapfile bs=1M count=2048
  chmod 600 /swapfile
  mkswap /swapfile >/dev/null
  swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
else
  log "Swap already present"
fi

# ---------------------------------------------------------------- firewall
# Oracle's stock images REJECT everything except SSH in the local INPUT chain.
# Opening the ports in the console Security List is NOT enough -- this half is
# the step everybody misses.
log "Opening ports 80 and 443 in the local firewall"
for port in 80 443; do
  if ! iptables -C INPUT -p tcp --dport "$port" -j ACCEPT 2>/dev/null; then
    iptables -I INPUT 1 -p tcp --dport "$port" -j ACCEPT
  fi
done
if command -v netfilter-persistent >/dev/null 2>&1; then
  netfilter-persistent save >/dev/null
elif [ -d /etc/iptables ]; then
  iptables-save > /etc/iptables/rules.v4
elif command -v firewall-cmd >/dev/null 2>&1; then
  firewall-cmd --permanent --add-service=http  >/dev/null || true
  firewall-cmd --permanent --add-service=https >/dev/null || true
  firewall-cmd --reload >/dev/null || true
fi

# UDP 443 for HTTP/3 -- optional, ignore failure
iptables -C INPUT -p udp --dport 443 -j ACCEPT 2>/dev/null \
  || iptables -I INPUT 1 -p udp --dport 443 -j ACCEPT || true

warn "Also add ingress rules for TCP 80 and 443 in the Oracle console:"
warn "  Networking > Virtual Cloud Networks > your VCN > Security Lists > Add Ingress Rule"
warn "  Source 0.0.0.0/0, IP Protocol TCP, Destination Port 80 (repeat for 443)"

# ------------------------------------------------------------------ secrets
ENV_FILE="$APP_DIR/.env.production"
if [ -f "$ENV_FILE" ]; then
  log ".env.production already exists -- leaving it alone"
else
  log "Generating .env.production with random secrets"
  cat > "$ENV_FILE" <<EOF
# generated by bootstrap-oracle.sh on $(date -Is)
SITE_ADDRESS=$SITE_ADDRESS
TLS_EMAIL=$TLS_EMAIL

MYSQL_ROOT_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')
MYSQL_USER=school
MYSQL_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')

SECRET_KEY=$(openssl rand -hex 32)
TOKEN_EXPIRE_HOURS=24

WEB_CONCURRENCY=$(( $(nproc) * 2 ))
EOF
  chmod 600 "$ENV_FILE"
  [ -n "$LOGIN_USER" ] && chown "$LOGIN_USER" "$ENV_FILE" || true
fi

# ------------------------------------------------------------------- launch
log "Building and starting the stack (first build takes a few minutes)"
cd "$APP_DIR"
chmod +x backup.sh 2>/dev/null || true
docker compose -f docker-compose.prod.yml --env-file .env.production up -d --build

log "Waiting for the API to report healthy"
DC="docker compose -f docker-compose.prod.yml --env-file .env.production"
for i in $(seq 1 60); do
  # ask the container directly, so this works with or without a hostname/TLS
  if $DC exec -T api python -c \
      "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=4)" \
      >/dev/null 2>&1; then
    printf '\n'
    break
  fi
  printf '.'
  sleep 5
  [ "$i" -eq 60 ] && warn "still not healthy -- check: $DC logs api"
done

# ------------------------------------------------------------------ backups
CRON_LINE="30 2 * * * cd $APP_DIR && ./backup.sh >> $APP_DIR/backups/backup.log 2>&1"
if ! crontab -l 2>/dev/null | grep -qF "$APP_DIR/backup.sh"; then
  log "Installing nightly backup cron (02:30)"
  ( crontab -l 2>/dev/null; echo "$CRON_LINE" ) | crontab -
fi

# -------------------------------------------------------------------- done
PUBLIC_IP="$(curl -fsS --max-time 5 https://checkip.amazonaws.com 2>/dev/null || echo 'YOUR_SERVER_IP')"
if [ "$SITE_ADDRESS" = ":80" ]; then
  URL="http://${PUBLIC_IP}"
else
  URL="https://${SITE_ADDRESS}"
fi

log "Done"
cat <<EOF
  API      $URL/health
  Swagger  $URL/docs

  First login: admin / admin123  -- CHANGE IT NOW.

  Logs     docker compose -f docker-compose.prod.yml --env-file .env.production logs -f api
  Restart  docker compose -f docker-compose.prod.yml --env-file .env.production restart api
  Backup   ./backup.sh

  Secrets are in $ENV_FILE (chmod 600). Keep a copy somewhere safe --
  if you lose MYSQL_PASSWORD you cannot reconnect to the existing database volume.
EOF
